export const TOOLTIPS = {
  COMPLETENESS: 'Percentage of mandatory requirements with evidence supporting them.',
  SUPPORTED: 'Evidence clearly addresses the requirement.',
  WEAK: 'Related evidence exists, but it is not sufficient to confidently satisfy the requirement.',
  AMBIGUOUS: 'Evidence exists, but its meaning or applicability is unclear.',
  MISSING: 'No relevant evidence was found in the supplied documents.',
  MANDATORY: 'The guideline indicates this requirement must be satisfied.',
  RECOMMENDED: 'The guideline recommends this information but does not make it mandatory.',
  STALE: 'This assessment was created using document versions that are no longer current.',
  CURRENT: 'This assessment reflects the latest versions of the guideline and application documents.',
  UNSUPPORTED_CLAIM: 'The application contains this claim, but no supporting evidence was found in the supplied documents.',
  AI_REASONING: 'Explanation generated by the AI to describe why the evidence was mapped to this requirement.',
  HUMAN_REVIEW: 'Human in the loop verification allowing reviewers to Confirm, Correct, or Reject AI findings.'
};
